-- GENERATED by `npm run db:bundle` -- do not edit by hand.
-- Source of truth is supabase/migrations/.
--
-- Paste this whole file into the Supabase SQL editor and run it once.
-- It is not idempotent: running it twice will fail on the create type
-- statements. That is intentional -- it should fail loudly rather than
-- half-apply.

begin;

-- ====================================================================
-- 20260721150000_initial_schema.sql
-- ====================================================================

-- Print queue: initial schema

create type user_role      as enum ('admin', 'operator');
create type owner_kind     as enum ('student', 'course', 'faculty', 'department');
create type printer_state  as enum ('available', 'printing', 'maintenance', 'retired');
create type job_status     as enum ('submitted', 'queued', 'printing', 'post_processing',
                                    'ready_for_pickup', 'collected', 'cancelled');
create type attempt_outcome as enum ('success', 'failed', 'cancelled');
create type failure_reason  as enum ('adhesion', 'layer_shift', 'clog', 'filament_runout',
                                     'power_loss', 'model_error', 'operator_error', 'other');

-- Staff who log in. id matches auth.users.id.
create table app_user (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text not null unique,
  full_name   text not null,
  role        user_role not null default 'operator',
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

-- Whoever a print belongs to. Not a login. This is what quotas and billing attach to.
create table owner (
  id           uuid primary key default gen_random_uuid(),
  display_name text not null,
  email        text,
  kind         owner_kind not null default 'student',
  course_code  text,
  quota_grams  integer,                       -- null = unlimited
  active       boolean not null default true,
  created_at   timestamptz not null default now()
);
create index owner_active_idx on owner (active) where active;

create table printer (
  id           uuid primary key default gen_random_uuid(),
  name         text not null unique,          -- e.g. 'mk4-01'
  model        text not null,
  nozzle_mm    numeric(3,1) not null default 0.4,
  build_volume text,
  state        printer_state not null default 'available',
  service_interval_hours integer not null default 250,
  notes        text,
  created_at   timestamptz not null default now()
);

create table spool (
  id              uuid primary key default gen_random_uuid(),
  material        text not null,              -- 'PLA', 'PETG', 'ABS', 'TPU'
  color_name      text not null,
  color_hex       text,
  brand           text,
  total_grams     integer not null check (total_grams > 0),
  remaining_grams integer not null check (remaining_grams >= 0),
  cost_cents      integer not null default 0 check (cost_cents >= 0),
  opened_on       date,
  retired         boolean not null default false,
  created_at      timestamptz not null default now(),
  constraint spool_remaining_lte_total check (remaining_grams <= total_grams)
);
create index spool_available_idx on spool (material, color_name)
  where not retired and remaining_grams > 0;

-- A request. One per thing someone wants printed.
create table job (
  id              uuid primary key default gen_random_uuid(),
  owner_id        uuid not null references owner(id) on delete restrict,
  submitted_by    uuid not null references app_user(id) on delete restrict,
  title           text not null,
  notes           text,
  file_path       text,                       -- Supabase Storage path to .gcode/.3mf
  material        text not null,
  color_preference text,
  est_minutes     integer not null check (est_minutes > 0),
  est_grams       integer not null check (est_grams > 0),
  needed_by       date,
  priority        integer not null default 0, -- higher sorts first in the queue
  status          job_status not null default 'submitted',
  shelf_location  text,
  collected_at    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index job_status_idx  on job (status);
create index job_owner_idx   on job (owner_id);
create index job_queue_idx   on job (priority desc, needed_by nulls last, created_at)
  where status in ('submitted', 'queued');

-- One run on one printer. This table is the source of truth for every metric.
create table attempt (
  id             uuid primary key default gen_random_uuid(),
  job_id         uuid not null references job(id) on delete cascade,
  printer_id     uuid not null references printer(id) on delete restrict,
  spool_id       uuid not null references spool(id) on delete restrict,
  started_by     uuid not null references app_user(id) on delete restrict,
  started_at     timestamptz not null default now(),
  expected_end   timestamptz not null,
  ended_at       timestamptz,
  outcome        attempt_outcome,
  failure_reason failure_reason,
  actual_grams   integer check (actual_grams >= 0),
  notes          text,
  constraint attempt_finalised_together check (
    (ended_at is null and outcome is null and actual_grams is null)
    or
    (ended_at is not null and outcome is not null and actual_grams is not null)
  ),
  constraint attempt_failure_reason_only_on_failure check (
    failure_reason is null or outcome = 'failed'
  )
);
create index attempt_job_idx     on attempt (job_id);
create index attempt_printer_idx on attempt (printer_id, started_at desc);
create unique index attempt_one_live_per_printer on attempt (printer_id)
  where ended_at is null;

create table maintenance_log (
  id              uuid primary key default gen_random_uuid(),
  printer_id      uuid not null references printer(id) on delete cascade,
  performed_by    uuid not null references app_user(id) on delete restrict,
  performed_at    timestamptz not null default now(),
  action          text not null,
  hours_at_service numeric(10,2),
  notes           text
);
create index maintenance_printer_idx on maintenance_log (printer_id, performed_at desc);

-- Derived: machine hours accumulated since the last logged service.
--
-- Every view below is security_invoker. Without it a view runs with its owner's
-- rights and ignores the RLS on the tables underneath, which would make
-- owner_usage -- names, course codes, spend -- readable with the anon key.
create view printer_service_status with (security_invoker = on) as
select
  p.id                as printer_id,
  p.name,
  p.state,
  p.service_interval_hours,
  m.last_service_at,
  coalesce(sum(
    extract(epoch from (coalesce(a.ended_at, now()) - a.started_at)) / 3600.0
  ) filter (where a.started_at > coalesce(m.last_service_at, '-infinity'::timestamptz)), 0)
    as hours_since_service
from printer p
left join lateral (
  select max(performed_at) as last_service_at
  from maintenance_log ml where ml.printer_id = p.id
) m on true
left join attempt a on a.printer_id = p.id
group by p.id, p.name, p.state, p.service_interval_hours, m.last_service_at;

-- Derived: reliability per printer, last 90 days.
create view printer_reliability with (security_invoker = on) as
select
  p.id   as printer_id,
  p.name,
  count(a.id)                                                as attempts,
  count(a.id) filter (where a.outcome = 'failed')             as failures,
  case when count(a.id) = 0 then 0
       else round(100.0 * count(a.id) filter (where a.outcome = 'failed') / count(a.id), 1)
  end                                                         as failure_rate_pct,
  coalesce(sum(a.actual_grams) filter (where a.outcome = 'failed'), 0) as wasted_grams
from printer p
left join attempt a
  on a.printer_id = p.id
 and a.ended_at > now() - interval '90 days'
group by p.id, p.name;

-- Derived: quota and cost per owner. Failed attempts are counted separately so
-- policy can decide whether to charge them.
create view owner_usage with (security_invoker = on) as
select
  o.id as owner_id,
  o.display_name,
  o.course_code,
  o.quota_grams,
  coalesce(sum(a.actual_grams) filter (where a.outcome = 'success'), 0) as grams_success,
  coalesce(sum(a.actual_grams) filter (where a.outcome = 'failed'), 0)  as grams_failed,
  coalesce(sum(
    a.actual_grams * (s.cost_cents::numeric / nullif(s.total_grams, 0))
  ), 0)::integer as cost_cents
from owner o
left join job j     on j.owner_id = o.id
left join attempt a on a.job_id = j.id and a.outcome is not null
left join spool s   on s.id = a.spool_id
group by o.id, o.display_name, o.course_code, o.quota_grams;

-- ====================================================================
-- 20260721150100_state_machine.sql
-- ====================================================================

-- Job status and printer state are consequences of attempts, not manual edits.

create or replace function touch_job_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

create trigger job_touch_updated_at
  before update on job
  for each row execute function touch_job_updated_at();

-- Starting an attempt puts the job and printer into 'printing'.
--
-- security definer is load-bearing. Trigger functions run as the invoking user,
-- so without it these cascading updates are filtered by the target table's RLS
-- policies and silently affect zero rows -- no error, just missing state.
create or replace function on_attempt_start() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  update job     set status = 'printing' where id = new.job_id;
  update printer set state  = 'printing' where id = new.printer_id;
  return new;
end $$;

create trigger attempt_start
  after insert on attempt
  for each row execute function on_attempt_start();

-- Finalising an attempt decrements the spool, frees the printer, and advances
-- the job. Filament is consumed on failure too.
--
-- security definer for the same reason as on_attempt_start, and it matters most
-- here: operators have no write policy on spool, so an operator finalising a
-- print would record actual_grams while the spool never decremented.
create or replace function on_attempt_finalise() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if old.ended_at is null and new.ended_at is not null then

    update spool
       set remaining_grams = greatest(0, remaining_grams - new.actual_grams),
           retired = (greatest(0, remaining_grams - new.actual_grams) = 0)
     where id = new.spool_id;

    update printer
       set state = case when state = 'printing' then 'available' else state end
     where id = new.printer_id;

    update job
       set status = case new.outcome
                      when 'success'   then 'post_processing'::job_status
                      when 'failed'    then 'queued'::job_status
                      when 'cancelled' then 'queued'::job_status
                    end
     where id = new.job_id;
  end if;
  return new;
end $$;

create trigger attempt_finalise
  after update on attempt
  for each row execute function on_attempt_finalise();

-- Guard: never start a print on a printer that is down or retired.
create or replace function guard_printer_available() returns trigger
language plpgsql as $$
declare s printer_state;
begin
  select state into s from printer where id = new.printer_id;
  if s in ('maintenance', 'retired') then
    raise exception 'Printer % is % and cannot accept jobs', new.printer_id, s;
  end if;
  return new;
end $$;

create trigger attempt_guard_printer
  before insert on attempt
  for each row execute function guard_printer_available();

-- Guard: don't start a print the spool cannot cover.
create or replace function guard_spool_sufficient() returns trigger
language plpgsql as $$
declare remaining integer; needed integer;
begin
  select remaining_grams into remaining from spool where id = new.spool_id;
  select est_grams       into needed    from job   where id = new.job_id;
  if remaining < needed then
    raise exception 'Spool has %g remaining but job needs %g', remaining, needed;
  end if;
  return new;
end $$;

create trigger attempt_guard_spool
  before insert on attempt
  for each row execute function guard_spool_sufficient();

-- ====================================================================
-- 20260721150200_rls_policies.sql
-- ====================================================================

-- Everyone who can log in is staff. Operators run the floor; admins also manage
-- inventory, printers, owners, and other users.

create or replace function current_role_is(required user_role) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from app_user
    where id = auth.uid() and active
      and (role = required or role = 'admin')
  );
$$;

create or replace function is_staff() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from app_user where id = auth.uid() and active);
$$;

alter table app_user        enable row level security;
alter table owner           enable row level security;
alter table printer         enable row level security;
alter table spool           enable row level security;
alter table job             enable row level security;
alter table attempt         enable row level security;
alter table maintenance_log enable row level security;

-- Read: any active staff member sees everything.
create policy staff_read_app_user   on app_user        for select using (is_staff());
create policy staff_read_owner      on owner           for select using (is_staff());
create policy staff_read_printer    on printer         for select using (is_staff());
create policy staff_read_spool      on spool           for select using (is_staff());
create policy staff_read_job        on job             for select using (is_staff());
create policy staff_read_attempt    on attempt         for select using (is_staff());
create policy staff_read_maint      on maintenance_log for select using (is_staff());

-- Operators run the day-to-day floor.
create policy op_write_job on job
  for all using (current_role_is('operator')) with check (current_role_is('operator'));

create policy op_write_attempt on attempt
  for all using (current_role_is('operator')) with check (current_role_is('operator'));

create policy op_write_maint on maintenance_log
  for all using (current_role_is('operator')) with check (current_role_is('operator'));

-- Operators may change printer state (to flag one down) but not create or delete.
create policy op_update_printer on printer
  for update using (current_role_is('operator')) with check (current_role_is('operator'));

-- Operators may decrement spools implicitly via triggers; explicit spool edits
-- and all inventory creation are admin-only.
create policy admin_all_printer on printer
  for all using (current_role_is('admin')) with check (current_role_is('admin'));

create policy admin_all_spool on spool
  for all using (current_role_is('admin')) with check (current_role_is('admin'));

create policy admin_all_owner on owner
  for all using (current_role_is('admin')) with check (current_role_is('admin'));

create policy admin_all_app_user on app_user
  for all using (current_role_is('admin')) with check (current_role_is('admin'));

-- ====================================================================
-- 20260721150300_realtime_and_grants.sql
-- ====================================================================

-- Realtime and grant hygiene.

-- Two TAs on the floor share the same timeline. Without these the floor view
-- goes stale between refreshes and double-starts become possible.
alter publication supabase_realtime add table attempt;
alter publication supabase_realtime add table job;

-- Realtime respects RLS, but only if the row payload can be matched against a
-- policy; replica identity full ships the whole row on update and delete.
alter table attempt replica identity full;
alter table job     replica identity full;

-- Nobody reaches this database unauthenticated. Supabase grants anon broad
-- access to the public schema by default; nothing here is public-facing, so
-- take it back. Views are security_invoker, so authenticated access is still
-- governed by each table's RLS policies.
revoke all on all tables    in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;

alter default privileges in schema public revoke all on tables    from anon;
alter default privileges in schema public revoke all on sequences from anon;
alter default privileges in schema public revoke all on functions from anon;

-- ====================================================================
-- 20260721150400_staff_provisioning.sql
-- ====================================================================

-- Staff provisioning.
--
-- Creating a TA account was: add the user, copy their auth uuid by hand, insert
-- a matching app_user row. Six chances to paste the wrong uuid. This makes the
-- app_user row appear automatically.
--
-- SECURITY: this grants operator access to every new auth.users row, so it is
-- only safe while public signup is disabled. Turn it off at
--   Authentication -> Sign In / Providers -> Email -> "Allow new users to sign up"
-- With signup off, the only way an auth.users row appears is an admin creating
-- it in the dashboard, which is the intent. If you ever re-enable public signup,
-- drop this trigger first or anyone with an email address becomes staff.

create or replace function handle_new_auth_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into app_user (id, email, full_name, role)
  values (
    new.id,
    new.email,
    -- Dashboard-created users have no metadata, so fall back to the local part
    -- of the address. Admins can correct the name afterwards.
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
      split_part(new.email, '@', 1)
    ),
    -- Never 'admin'. Promote deliberately, with the statement below.
    'operator'
  )
  on conflict (id) do nothing;
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_auth_user();

-- Promote someone to admin:
--   update app_user set role = 'admin' where email = 'you@hc.edu';
--
-- Revoke access without deleting history (app_user is referenced by job and
-- attempt, so deleting is blocked on purpose):
--   update app_user set active = false where email = 'former-ta@hc.edu';

-- ====================================================================
-- 20260721150500_job_files_storage.sql
-- ====================================================================

-- Storage for uploaded .gcode / .3mf / .stl files attached to a job.
--
-- Private bucket. These are student coursework and the dashboard is staff-only;
-- nothing here should be reachable without a session.

insert into storage.buckets (id, name, public, file_size_limit)
values ('job-files', 'job-files', false, 209715200)  -- 200 MB
on conflict (id) do nothing;

-- No allowed_mime_types filter on purpose: browsers report .gcode and .3mf
-- inconsistently (often application/octet-stream or an empty string), so a
-- mime allowlist rejects legitimate uploads. The size cap is the real guard.

-- Same rule as every other table: any active staff member, nobody else.
-- storage.objects already has RLS enabled by Supabase.
create policy "staff read job files" on storage.objects
  for select using (bucket_id = 'job-files' and public.is_staff());

create policy "staff upload job files" on storage.objects
  for insert with check (bucket_id = 'job-files' and public.is_staff());

create policy "staff update job files" on storage.objects
  for update using (bucket_id = 'job-files' and public.is_staff())
  with check (bucket_id = 'job-files' and public.is_staff());

-- Deleting the file does not delete the job or its attempts. The job keeps its
-- file_path, which will simply resolve to nothing -- acceptable, because the
-- print history is the record that matters, not the source file.
create policy "staff delete job files" on storage.objects
  for delete using (bucket_id = 'job-files' and public.is_staff());

-- ====================================================================
-- 20260721150600_three_roles.sql
-- ====================================================================

-- Three roles, replacing the original "any active staff sees everything" model.
--
--   admin    -- everything, including creating accounts and setting roles.
--   operator -- everything except account management: the floor, printers,
--               inventory, owners, and full control of every job.
--   ta       -- creates jobs and owners; reads every job but edits only their
--               own; no access to printers, inventory, reports, or other staff.
--
-- RLS is the real boundary. The app's role checks and hidden nav are only there
-- so a TA gets a locked door instead of a silent empty result.

alter type user_role add value if not exists 'ta';

-- Helpers. None reference the literal 'ta', so this migration never uses the
-- new enum value within its own transaction -- Postgres forbids using a value
-- added to a pre-existing enum in the same transaction.
create or replace function is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from app_user
    where id = auth.uid() and active and role = 'admin'
  );
$$;

create or replace function can_operate() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from app_user
    where id = auth.uid() and active and role in ('admin', 'operator')
  );
$$;

-- Unchanged in meaning (any active staff), restated so this file is complete.
create or replace function is_staff() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from app_user where id = auth.uid() and active);
$$;

-- Out with the two-role policies.
drop policy if exists staff_read_app_user on app_user;
drop policy if exists admin_all_app_user   on app_user;
drop policy if exists staff_read_owner   on owner;
drop policy if exists admin_all_owner     on owner;
drop policy if exists staff_read_printer on printer;
drop policy if exists op_update_printer   on printer;
drop policy if exists admin_all_printer   on printer;
drop policy if exists staff_read_spool   on spool;
drop policy if exists admin_all_spool     on spool;
drop policy if exists staff_read_job      on job;
drop policy if exists op_write_job        on job;
drop policy if exists staff_read_attempt on attempt;
drop policy if exists op_write_attempt    on attempt;
drop policy if exists staff_read_maint   on maintenance_log;
drop policy if exists op_write_maint      on maintenance_log;

-- app_user: a TA sees only their own row. Operators and admins see all staff
-- (names show up in job and attempt history). Only admins create or change
-- accounts, which includes setting roles.
create policy app_user_read_self_or_operate on app_user
  for select using (id = auth.uid() or can_operate());
create policy app_user_admin_write on app_user
  for all using (is_admin()) with check (is_admin());

-- owner: every staffer reads owners and creates them (a TA adds a student
-- mid-submission). Editing or deactivating an existing owner is operator/admin.
create policy owner_read on owner
  for select using (is_staff());
create policy owner_create on owner
  for insert with check (is_staff());
create policy owner_operate_update on owner
  for update using (can_operate()) with check (can_operate());
create policy owner_operate_delete on owner
  for delete using (can_operate());

-- printer, spool, maintenance_log: operator/admin only. A TA has no access at
-- all -- not even read.
create policy printer_operate_all on printer
  for all using (can_operate()) with check (can_operate());
create policy spool_operate_all on spool
  for all using (can_operate()) with check (can_operate());
create policy maint_operate_all on maintenance_log
  for all using (can_operate()) with check (can_operate());

-- job: all staff read every job. Anyone creates a job as themselves. Operators
-- and admins update any job (they drive the status machine); a TA updates only
-- the jobs they submitted. Nobody deletes a job -- there is no delete policy.
create policy job_read on job
  for select using (is_staff());
create policy job_create_own on job
  for insert with check (submitted_by = auth.uid());
create policy job_update on job
  for update
  using (can_operate() or submitted_by = auth.uid())
  with check (can_operate() or submitted_by = auth.uid());

-- attempt: all staff read (attempt history shows on job detail, which every
-- staffer can open). Only operators and admins write -- starting and finishing
-- a print is their work.
create policy attempt_read on attempt
  for select using (is_staff());
create policy attempt_operate_write on attempt
  for all using (can_operate()) with check (can_operate());

-- owner_usage feeds the owners page, which TAs can see -- including per-owner
-- cost, which is derived from spool prices a TA cannot read. Flip the view to
-- run with definer rights so the aggregate computes regardless. It exposes only
-- rolled-up totals per owner, never the spool inventory, and anon was already
-- revoked. This relies on public signup staying disabled, which the
-- provisioning trigger already requires.
alter view owner_usage set (security_invoker = off);

-- New accounts start as the least-privileged role. An admin promotes
-- deliberately.
create or replace function handle_new_auth_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into app_user (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
      split_part(new.email, '@', 1)
    ),
    'ta'
  )
  on conflict (id) do nothing;
  return new;
end $$;

-- The old two-role helper is unreferenced now.
drop function if exists current_role_is(user_role);

-- ====================================================================
-- 20260721150700_harden_job_and_storage.sql
-- ====================================================================

-- Security hardening found in review. Both close direct-API bypasses that the
-- app UI never exposes but an authenticated TA could reach with their own JWT.

-- 1. job.status may only be changed by an operator/admin -- except a submitter
--    cancelling their own job. Without this, the job_update RLS policy (which
--    can't restrict columns) lets a TA PATCH status on their own job and
--    self-approve, skipping operator approval and the quota gate.
--
--    The attempt-driven transitions are safe: they run inside operator actions,
--    where can_operate() is true. TAs cannot write attempts at all.
create or replace function guard_job_status_transition() returns trigger
language plpgsql security invoker set search_path = public as $$
begin
  if can_operate() then
    return new;
  end if;
  if new.status = 'cancelled' and old.submitted_by = auth.uid() then
    return new;
  end if;
  raise exception 'You do not have permission to change this job''s status.';
end $$;

create trigger job_guard_status
  before update on job
  for each row
  when (new.status is distinct from old.status)
  execute function guard_job_status_transition();

-- 2. Tighten the job-files bucket. Staff still upload (their own jobs) and read
--    (all jobs are staff-readable), but:
--    - update is operator/admin only (the app never updates a file anyway);
--    - delete is the uploader or an operator, so a TA's orphan-cleanup of their
--      own failed upload still works, but a TA cannot wipe other jobs' files.
--    storage.objects.owner is the uploader's uid.
drop policy if exists "staff update job files" on storage.objects;
drop policy if exists "staff delete job files" on storage.objects;

create policy "operate update job files" on storage.objects
  for update using (bucket_id = 'job-files' and public.can_operate())
  with check (bucket_id = 'job-files' and public.can_operate());

create policy "delete own or operate job files" on storage.objects
  for delete using (
    bucket_id = 'job-files'
    and (owner = auth.uid() or public.can_operate())
  );

-- ====================================================================
-- 20260721150800_health_ping.sql
-- ====================================================================

-- Keep-alive ping for /api/health.
--
-- The health endpoint runs unauthenticated (as the anon role), and
-- 20260721150300 revoked every anon privilege on public objects. So a plain
-- "select from <table>" as anon is a hard permission error, not an RLS-empty
-- result -- which is why the endpoint reported db:"error".
--
-- This is a dedicated no-data function the anon role may call. Executing it is a
-- real query against Postgres, so it keeps a free-tier project awake, but it
-- touches no table and returns nothing sensitive.

create or replace function public.health_ping() returns boolean
language sql stable as $$ select true $$;

grant execute on function public.health_ping() to anon, authenticated;

commit;
